// Defining my API routes

// Get all TV Shows

### 
GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows
Content-Type: application/json
Accept: application/json

### 
//
//Get TV Shows Stats
GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows/stats
Content-Type: application/json
Accept: application/json

### 
//Get Running Fox TV Shows
GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows/runningFoxTvShows
Content-Type: application/json
Accept: application/json

### 
//Get Single TV Show by ID
GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows/667c45dc7451548211a1d66d
Content-Type: application/json
Accept: application/json

### 
//Create a New TV Show
POST https://cse341-project2-l44o.onrender.com/api/v1/tv-shows
Content-Type: application/json
Accept: application/json

{
  "url": "http://example.com",
  "name": "Example Show",
  "type": "Scripted",
  "language": "English",
  "genres": ["Drama"],
  "status": "Running",
  "runtime": 60,
  "premiered": "2024-01-01",
  "officialSite": "http://example.com",
  "schedule": {
    "time": "21:00",
    "days": ["Monday"]
  },
  "rating": {
    "average": 7.5
  },
  "weight": 100,
  "network": {
    "id": 1,
    "name": "Example Network",
    "country": {
      "name": "United States",
      "code": "US",
      "timezone": "America/New_York"
    }
  },
  "externals": {
    "tvrage": 12345,
    "thetvdb": 67890,
    "imdb": "tt1234567"
  },
  "image": {
    "medium": "http://example.com/medium.jpg",
    "original": "http://example.com/original.jpg"
  },
  "summary": "This is an example show.",
  "updated": 1620000000,
  "_links": {
    "self": {
      "href": "http://example.com/shows/1"
    },
    "previousepisode": {
      "href": "http://example.com/episodes/1"
    }
  }
}

### 
//Update a TV Show by ID
PUT https://cse341-project2-l44o.onrender.com/api/v1/tv-shows/667c45dc7451548211a1d655
Content-Type: application/json
Accept: application/json

{
  "url": "http://example.com",
  "name": "Updated Show",
  "type": "Scripted",
  "language": "English",
  "genres": ["Drama"],
  "status": "Running",
  "runtime": 60,
  "premiered": "2024-01-01",
  "officialSite": "http://example.com",
  "schedule": {
    "time": "21:00",
    "days": ["Monday"]
  },
  "rating": {
    "average": 8.0
  },
  "weight": 100,
  "network": {
    "id": 1,
    "name": "Example Network",
    "country": {
      "name": "United States",
      "code": "US",
      "timezone": "America/New_York"
    }
  },
  "externals": {
    "tvrage": 12345,
    "thetvdb": 67890,
    "imdb": "tt1234567"
  },
  "image": {
    "medium": "http://example.com/medium.jpg",
    "original": "http://example.com/original.jpg"
  },
  "summary": "This is an updated show.",
  "updated": 1620000000,
  "_links": {
    "self": {
      "href": "http://example.com/shows/1"
    },
    "previousepisode": {
      "href": "http://example.com/episodes/1"
    }
  }
}

### 
//Delete a TV Show by ID
DELETE https://cse341-project2-l44o.onrender.com/api/v1/tv-shows/667c45dc7451548211a1d655
Content-Type: application/json
Accept: application/json

###

// ----------------------- Aggregation routes ----------------- /

// Getting tv-shows stats

GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows/stats HTTP/1.1

###

// Getting shows that are running on FOX
GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows/runningFoxTvShows HTTP/1.1

### 

// --------------------- QUERY ROUTE ----------------------/

// Getting  the name, type, language, genres, url, network, 
// of all tv shows sorted by thier name

GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows?sort=name&fields=name,type,language,genres,url,network HTTP/1.1

###

// Getting all tv shows from page 2 with a 15 document result

GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows?page=2&limit=15 HTTP/1.1

###

// getting all shows from the network with id of 9

GET https://cse341-project2-l44o.onrender.com/api/v1/tv-shows?network.id=9 HTTP/1.1